myshell: myshell.c shell_func.c shell_func.h
	gcc -Wall myshell.c shell_func.c -o myshell
	mv myshell ../bin/myshell
	../bin/myshell

test: test.c
	gcc -o test test.c
	mv test ../bin/test
	../bin/test first second third

test2: test2.c
	gcc -o test2 test2.c
	mv test2 ../bin/test2
	../bin/test2 a1 a2

test3: test3.c
	gcc -o test3 test3.c
	mv test3 ../bin/test3
	../bin/test3
