myshell: myshell.c shell_func.c shell_func.h
	gcc -Wall myshell.c shell_func.c -o myshell
	mv myshell ../bin/myshell
	../bin/myshell

test: test.c
	gcc -o test test.c
	mv test ../bin/test
	../bin/test arg1 arg2
