myshell: myshell.c
	gcc -o myshell myshell.c shell_func.c
	mv myshell ../bin/myshell
	../bin/myshell

test: test.c
	gcc -o test test.c
	mv test ../bin/test
	../bin/test first second third

test2: test2.c
	gcc -o test2 test2.c
	mv test2 ../bin/test2
	../bin/test2 a1 a2
